main: io.offbit.obeconomy.PluginEntry
name: OBEconomy
version: 1.0.0
description: This plugin adds gold nuggets as main economy.
api-version: 1.13
author: beavurus
depend:  [Vault]
load: STARTUP
commands:
  balance:
    description: check your balance
    usage: /<command>
  brik:
    description: economy admin entry command
    usage: "Usage: /<command> [add|remove] PlayerName {amount}"
